version: '3.8'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codealpha-container
    image: codealpha-webserver
    ports:
      - "8080:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3
    labels:
      - "project=codealpha"
      - "task=docker-webserver"
      - "author=Oluwatobi Ogundimu"